/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

// Import Routes

import { Route as rootRoute } from './routes/__root'
import { Route as appRouteImport } from './routes/(app)/route'
import { Route as AdminIndexImport } from './routes/admin/index'
import { Route as appIndexImport } from './routes/(app)/index'
import { Route as appAboutImport } from './routes/(app)/about'
import { Route as appListsIndexImport } from './routes/(app)/lists/index'

// Create/Update Routes

const appRouteRoute = appRouteImport.update({
  id: '/(app)',
  getParentRoute: () => rootRoute,
} as any)

const AdminIndexRoute = AdminIndexImport.update({
  id: '/admin/',
  path: '/admin/',
  getParentRoute: () => rootRoute,
} as any)

const appIndexRoute = appIndexImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => appRouteRoute,
} as any)

const appAboutRoute = appAboutImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => appRouteRoute,
} as any)

const appListsIndexRoute = appListsIndexImport.update({
  id: '/lists/',
  path: '/lists/',
  getParentRoute: () => appRouteRoute,
} as any)

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/(app)': {
      id: '/(app)'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof appRouteImport
      parentRoute: typeof rootRoute
    }
    '/(app)/about': {
      id: '/(app)/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof appAboutImport
      parentRoute: typeof appRouteImport
    }
    '/(app)/': {
      id: '/(app)/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof appIndexImport
      parentRoute: typeof appRouteImport
    }
    '/admin/': {
      id: '/admin/'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminIndexImport
      parentRoute: typeof rootRoute
    }
    '/(app)/lists/': {
      id: '/(app)/lists/'
      path: '/lists'
      fullPath: '/lists'
      preLoaderRoute: typeof appListsIndexImport
      parentRoute: typeof appRouteImport
    }
  }
}

// Create and export the route tree

interface appRouteRouteChildren {
  appAboutRoute: typeof appAboutRoute
  appIndexRoute: typeof appIndexRoute
  appListsIndexRoute: typeof appListsIndexRoute
}

const appRouteRouteChildren: appRouteRouteChildren = {
  appAboutRoute: appAboutRoute,
  appIndexRoute: appIndexRoute,
  appListsIndexRoute: appListsIndexRoute,
}

const appRouteRouteWithChildren = appRouteRoute._addFileChildren(
  appRouteRouteChildren,
)

export interface FileRoutesByFullPath {
  '/': typeof appIndexRoute
  '/about': typeof appAboutRoute
  '/admin': typeof AdminIndexRoute
  '/lists': typeof appListsIndexRoute
}

export interface FileRoutesByTo {
  '/about': typeof appAboutRoute
  '/': typeof appIndexRoute
  '/admin': typeof AdminIndexRoute
  '/lists': typeof appListsIndexRoute
}

export interface FileRoutesById {
  __root__: typeof rootRoute
  '/(app)': typeof appRouteRouteWithChildren
  '/(app)/about': typeof appAboutRoute
  '/(app)/': typeof appIndexRoute
  '/admin/': typeof AdminIndexRoute
  '/(app)/lists/': typeof appListsIndexRoute
}

export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/about' | '/admin' | '/lists'
  fileRoutesByTo: FileRoutesByTo
  to: '/about' | '/' | '/admin' | '/lists'
  id:
    | '__root__'
    | '/(app)'
    | '/(app)/about'
    | '/(app)/'
    | '/admin/'
    | '/(app)/lists/'
  fileRoutesById: FileRoutesById
}

export interface RootRouteChildren {
  appRouteRoute: typeof appRouteRouteWithChildren
  AdminIndexRoute: typeof AdminIndexRoute
}

const rootRouteChildren: RootRouteChildren = {
  appRouteRoute: appRouteRouteWithChildren,
  AdminIndexRoute: AdminIndexRoute,
}

export const routeTree = rootRoute
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

/* ROUTE_MANIFEST_START
{
  "routes": {
    "__root__": {
      "filePath": "__root.tsx",
      "children": [
        "/(app)",
        "/admin/"
      ]
    },
    "/(app)": {
      "filePath": "(app)/route.tsx",
      "children": [
        "/(app)/about",
        "/(app)/",
        "/(app)/lists/"
      ]
    },
    "/(app)/about": {
      "filePath": "(app)/about.tsx",
      "parent": "/(app)"
    },
    "/(app)/": {
      "filePath": "(app)/index.tsx",
      "parent": "/(app)"
    },
    "/admin/": {
      "filePath": "admin/index.tsx"
    },
    "/(app)/lists/": {
      "filePath": "(app)/lists/index.tsx",
      "parent": "/(app)"
    }
  }
}
ROUTE_MANIFEST_END */
