/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

// Import Routes

import { Route as rootRoute } from './routes/__root'
import { Route as AdminRouteImport } from './routes/admin/route'
import { Route as authRouteImport } from './routes/(auth)/route'
import { Route as appRouteImport } from './routes/(app)/route'
import { Route as AdminIndexImport } from './routes/admin/index'
import { Route as appIndexImport } from './routes/(app)/index'
import { Route as AdminUsersImport } from './routes/admin/users'
import { Route as authRegisterImport } from './routes/(auth)/register'
import { Route as authLoginImport } from './routes/(auth)/login'
import { Route as authForgotPasswordImport } from './routes/(auth)/forgot-password'
import { Route as appAboutImport } from './routes/(app)/about'
import { Route as appAuthenticatedImport } from './routes/(app)/_authenticated'
import { Route as appListsIndexImport } from './routes/(app)/lists/index'
import { Route as appAuthenticatedProfileImport } from './routes/(app)/_authenticated.profile'

// Create/Update Routes

const AdminRouteRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRoute,
} as any)

const authRouteRoute = authRouteImport.update({
  id: '/(auth)',
  getParentRoute: () => rootRoute,
} as any)

const appRouteRoute = appRouteImport.update({
  id: '/(app)',
  getParentRoute: () => rootRoute,
} as any)

const AdminIndexRoute = AdminIndexImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AdminRouteRoute,
} as any)

const appIndexRoute = appIndexImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => appRouteRoute,
} as any)

const AdminUsersRoute = AdminUsersImport.update({
  id: '/users',
  path: '/users',
  getParentRoute: () => AdminRouteRoute,
} as any)

const authRegisterRoute = authRegisterImport.update({
  id: '/register',
  path: '/register',
  getParentRoute: () => authRouteRoute,
} as any)

const authLoginRoute = authLoginImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => authRouteRoute,
} as any)

const authForgotPasswordRoute = authForgotPasswordImport.update({
  id: '/forgot-password',
  path: '/forgot-password',
  getParentRoute: () => authRouteRoute,
} as any)

const appAboutRoute = appAboutImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => appRouteRoute,
} as any)

const appAuthenticatedRoute = appAuthenticatedImport.update({
  id: '/_authenticated',
  getParentRoute: () => appRouteRoute,
} as any)

const appListsIndexRoute = appListsIndexImport.update({
  id: '/lists/',
  path: '/lists/',
  getParentRoute: () => appRouteRoute,
} as any)

const appAuthenticatedProfileRoute = appAuthenticatedProfileImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => appAuthenticatedRoute,
} as any)

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/(app)': {
      id: '/(app)'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof appRouteImport
      parentRoute: typeof rootRoute
    }
    '/(auth)': {
      id: '/(auth)'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof authRouteImport
      parentRoute: typeof rootRoute
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRoute
    }
    '/(app)/_authenticated': {
      id: '/(app)/_authenticated'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof appAuthenticatedImport
      parentRoute: typeof appRouteImport
    }
    '/(app)/about': {
      id: '/(app)/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof appAboutImport
      parentRoute: typeof appRouteImport
    }
    '/(auth)/forgot-password': {
      id: '/(auth)/forgot-password'
      path: '/forgot-password'
      fullPath: '/forgot-password'
      preLoaderRoute: typeof authForgotPasswordImport
      parentRoute: typeof authRouteImport
    }
    '/(auth)/login': {
      id: '/(auth)/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof authLoginImport
      parentRoute: typeof authRouteImport
    }
    '/(auth)/register': {
      id: '/(auth)/register'
      path: '/register'
      fullPath: '/register'
      preLoaderRoute: typeof authRegisterImport
      parentRoute: typeof authRouteImport
    }
    '/admin/users': {
      id: '/admin/users'
      path: '/users'
      fullPath: '/admin/users'
      preLoaderRoute: typeof AdminUsersImport
      parentRoute: typeof AdminRouteImport
    }
    '/(app)/': {
      id: '/(app)/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof appIndexImport
      parentRoute: typeof appRouteImport
    }
    '/admin/': {
      id: '/admin/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminIndexImport
      parentRoute: typeof AdminRouteImport
    }
    '/(app)/_authenticated/profile': {
      id: '/(app)/_authenticated/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof appAuthenticatedProfileImport
      parentRoute: typeof appAuthenticatedImport
    }
    '/(app)/lists/': {
      id: '/(app)/lists/'
      path: '/lists'
      fullPath: '/lists'
      preLoaderRoute: typeof appListsIndexImport
      parentRoute: typeof appRouteImport
    }
  }
}

// Create and export the route tree

interface appAuthenticatedRouteChildren {
  appAuthenticatedProfileRoute: typeof appAuthenticatedProfileRoute
}

const appAuthenticatedRouteChildren: appAuthenticatedRouteChildren = {
  appAuthenticatedProfileRoute: appAuthenticatedProfileRoute,
}

const appAuthenticatedRouteWithChildren =
  appAuthenticatedRoute._addFileChildren(appAuthenticatedRouteChildren)

interface appRouteRouteChildren {
  appAuthenticatedRoute: typeof appAuthenticatedRouteWithChildren
  appAboutRoute: typeof appAboutRoute
  appIndexRoute: typeof appIndexRoute
  appListsIndexRoute: typeof appListsIndexRoute
}

const appRouteRouteChildren: appRouteRouteChildren = {
  appAuthenticatedRoute: appAuthenticatedRouteWithChildren,
  appAboutRoute: appAboutRoute,
  appIndexRoute: appIndexRoute,
  appListsIndexRoute: appListsIndexRoute,
}

const appRouteRouteWithChildren = appRouteRoute._addFileChildren(
  appRouteRouteChildren,
)

interface authRouteRouteChildren {
  authForgotPasswordRoute: typeof authForgotPasswordRoute
  authLoginRoute: typeof authLoginRoute
  authRegisterRoute: typeof authRegisterRoute
}

const authRouteRouteChildren: authRouteRouteChildren = {
  authForgotPasswordRoute: authForgotPasswordRoute,
  authLoginRoute: authLoginRoute,
  authRegisterRoute: authRegisterRoute,
}

const authRouteRouteWithChildren = authRouteRoute._addFileChildren(
  authRouteRouteChildren,
)

interface AdminRouteRouteChildren {
  AdminUsersRoute: typeof AdminUsersRoute
  AdminIndexRoute: typeof AdminIndexRoute
}

const AdminRouteRouteChildren: AdminRouteRouteChildren = {
  AdminUsersRoute: AdminUsersRoute,
  AdminIndexRoute: AdminIndexRoute,
}

const AdminRouteRouteWithChildren = AdminRouteRoute._addFileChildren(
  AdminRouteRouteChildren,
)

export interface FileRoutesByFullPath {
  '/': typeof appIndexRoute
  '/admin': typeof AdminRouteRouteWithChildren
  '': typeof appAuthenticatedRouteWithChildren
  '/about': typeof appAboutRoute
  '/forgot-password': typeof authForgotPasswordRoute
  '/login': typeof authLoginRoute
  '/register': typeof authRegisterRoute
  '/admin/users': typeof AdminUsersRoute
  '/admin/': typeof AdminIndexRoute
  '/profile': typeof appAuthenticatedProfileRoute
  '/lists': typeof appListsIndexRoute
}

export interface FileRoutesByTo {
  '/': typeof appIndexRoute
  '': typeof appAuthenticatedRouteWithChildren
  '/about': typeof appAboutRoute
  '/forgot-password': typeof authForgotPasswordRoute
  '/login': typeof authLoginRoute
  '/register': typeof authRegisterRoute
  '/admin/users': typeof AdminUsersRoute
  '/admin': typeof AdminIndexRoute
  '/profile': typeof appAuthenticatedProfileRoute
  '/lists': typeof appListsIndexRoute
}

export interface FileRoutesById {
  __root__: typeof rootRoute
  '/(app)': typeof appRouteRouteWithChildren
  '/(auth)': typeof authRouteRouteWithChildren
  '/admin': typeof AdminRouteRouteWithChildren
  '/(app)/_authenticated': typeof appAuthenticatedRouteWithChildren
  '/(app)/about': typeof appAboutRoute
  '/(auth)/forgot-password': typeof authForgotPasswordRoute
  '/(auth)/login': typeof authLoginRoute
  '/(auth)/register': typeof authRegisterRoute
  '/admin/users': typeof AdminUsersRoute
  '/(app)/': typeof appIndexRoute
  '/admin/': typeof AdminIndexRoute
  '/(app)/_authenticated/profile': typeof appAuthenticatedProfileRoute
  '/(app)/lists/': typeof appListsIndexRoute
}

export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | ''
    | '/about'
    | '/forgot-password'
    | '/login'
    | '/register'
    | '/admin/users'
    | '/admin/'
    | '/profile'
    | '/lists'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | ''
    | '/about'
    | '/forgot-password'
    | '/login'
    | '/register'
    | '/admin/users'
    | '/admin'
    | '/profile'
    | '/lists'
  id:
    | '__root__'
    | '/(app)'
    | '/(auth)'
    | '/admin'
    | '/(app)/_authenticated'
    | '/(app)/about'
    | '/(auth)/forgot-password'
    | '/(auth)/login'
    | '/(auth)/register'
    | '/admin/users'
    | '/(app)/'
    | '/admin/'
    | '/(app)/_authenticated/profile'
    | '/(app)/lists/'
  fileRoutesById: FileRoutesById
}

export interface RootRouteChildren {
  appRouteRoute: typeof appRouteRouteWithChildren
  authRouteRoute: typeof authRouteRouteWithChildren
  AdminRouteRoute: typeof AdminRouteRouteWithChildren
}

const rootRouteChildren: RootRouteChildren = {
  appRouteRoute: appRouteRouteWithChildren,
  authRouteRoute: authRouteRouteWithChildren,
  AdminRouteRoute: AdminRouteRouteWithChildren,
}

export const routeTree = rootRoute
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

/* ROUTE_MANIFEST_START
{
  "routes": {
    "__root__": {
      "filePath": "__root.tsx",
      "children": [
        "/(app)",
        "/(auth)",
        "/admin"
      ]
    },
    "/(app)": {
      "filePath": "(app)/route.tsx",
      "children": [
        "/(app)/_authenticated",
        "/(app)/about",
        "/(app)/",
        "/(app)/lists/"
      ]
    },
    "/(auth)": {
      "filePath": "(auth)/route.tsx",
      "children": [
        "/(auth)/forgot-password",
        "/(auth)/login",
        "/(auth)/register"
      ]
    },
    "/admin": {
      "filePath": "admin/route.tsx",
      "children": [
        "/admin/users",
        "/admin/"
      ]
    },
    "/(app)/_authenticated": {
      "filePath": "(app)/_authenticated.tsx",
      "parent": "/(app)",
      "children": [
        "/(app)/_authenticated/profile"
      ]
    },
    "/(app)/about": {
      "filePath": "(app)/about.tsx",
      "parent": "/(app)"
    },
    "/(auth)/forgot-password": {
      "filePath": "(auth)/forgot-password.tsx",
      "parent": "/(auth)"
    },
    "/(auth)/login": {
      "filePath": "(auth)/login.tsx",
      "parent": "/(auth)"
    },
    "/(auth)/register": {
      "filePath": "(auth)/register.tsx",
      "parent": "/(auth)"
    },
    "/admin/users": {
      "filePath": "admin/users.tsx",
      "parent": "/admin"
    },
    "/(app)/": {
      "filePath": "(app)/index.tsx",
      "parent": "/(app)"
    },
    "/admin/": {
      "filePath": "admin/index.tsx",
      "parent": "/admin"
    },
    "/(app)/_authenticated/profile": {
      "filePath": "(app)/_authenticated.profile.tsx",
      "parent": "/(app)/_authenticated"
    },
    "/(app)/lists/": {
      "filePath": "(app)/lists/index.tsx",
      "parent": "/(app)"
    }
  }
}
ROUTE_MANIFEST_END */
